### ISSUE TITLE
Run demo to display this error

### ISSUE THREAD

**Issue by notehel** [eggsampler/acme#14]
Run demo to display this error
The file account.json exists,

account.json------------------------------------

{"privateKey":{"Curve":{"P":115792089210356248762697446949407573530086143415290314195533631308867097853951,"N":115792089210356248762697446949407573529996955224135760342422259061068512044369,"B":41058363725152142129326129780047268409114441015993725554835256314039467401291,"Gx":48439561293906451759052585252797914202762949526041747995844080717082404635286,"Gy":36134250956749795798585127919587881956611106672985015071877198253568414405109,"BitSize":256,"Name":"P-256"},"X":41178151817122239433356222411489439804372075567845109400219748159912996694009,"Y":24826081506640848655063590742050469683068455586774664253397080240470785724093,"D":862554419784806997692513240127725874318132151522119685122473463896162066354},"url":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/11906772"}

**Comment by notehel** [comment]
2019/12/26 18:52:55 Connecting to acme directory url: https://acme-staging-v02.api.letsencrypt.org/directory
2019/12/26 18:52:56 Loading account file D:\DevMax\Go\work\src\acme\bin\account.json
2019/12/26 18:52:56 Error loading existing account: error parsing account file "D:\\work\\src\\acme\\bin\\account.json": json: cannot unmarshal object into Go struct field PrivateKey.privateKey.Curve of type elliptic.Curve
2019/12/26 18:52:56 Creating new account

**Comment by notehel** [comment]
2019/12/26 18:52:55 Connecting to acme directory url: https://acme-staging-v02.api.letsencrypt.org/directory
2019/12/26 18:52:56 Loading account file D:\work\src\acme\bin\account.json
2019/12/26 18:52:56 Error loading existing account: error parsing account file "D:\\work\\src\\acme\\bin\\account.json": json: cannot unmarshal object into Go struct field PrivateKey.privateKey.Curve of type elliptic.Curve
2019/12/26 18:52:56 Creating new account

**Comment by eggsampler** [comment]
I've just pushed a change to update the example and change how the key is saved/loaded. Let me know if there's any further issues.
