### ISSUE TITLE
NewOrder fails agains pebble

### ISSUE THREAD

**Issue by ibukanov** [eggsampler/acme#15]
I am trying to test against pebble, https://github.com/letsencrypt/pebble , that I run locally. I am getting an error at https://github.com/eggsampler/acme/blob/master/order.go#L20 :

`acme: error code 400 "urn:ietf:params:acme:error:malformed": Key ID (kid) in JWS header missing expected URL prefix
`

Any clues?

**Comment by ibukanov** [comment]
The same code works find against the production LetsEncrypt service.

**Comment by eggsampler** [comment]
Sorry for not getting back to you sooner.

I've just checked the pebble test in travis and locally via `make clean pebble` and both succeed without issue. Are you able to provide any more info as to the git revision you are using and how you are running the test?

**Comment by eggsampler** [comment]
I'm going to close this for now without a reproduction, if you get a chance to come back to this please let me know!
