### ISSUE TITLE
DNS-challenge

### ISSUE THREAD

**Issue by crenanlouzada** [eggsampler/acme#16]
please, would you have an example with dns-challenge besides http-challenge?

**Comment by crenanlouzada** [comment]
to show the idea, I tried to change the line of code (certbot.go) where it says:

chal, ok: = auth.ChallengeMap [acme.ChallengeTypeHTTP01]
to
chal, ok: = auth.ChallengeMap [acme.ChallengeTypeDNS01]

and put the entry in the dns but it doesn't work based on the content of (tokenFile) coming from $ {webroot} /. well-known

**Comment by eggsampler** [comment]
Hi

Thanks for the suggestion, I'll look at adding an example using the dns challenge method. The problem here being it's usually much more complex to fulfill the challenge so maybe it will just prompt the user instead.

**Comment by eggsampler** [comment]
I've added a section to the certbot example which outlines this. Due to the complex nature of actually fulfilling DNS challenges, I can't think of a nice way to actually demonstrate this further. Might come back in future with any further thoughts or suggestions.
