### ISSUE TITLE
Renewal HowTo

### ISSUE THREAD

**Issue by ngortheone** [eggsampler/acme#22]
Hey there!

Thanks for the awesome minimalist library!

I was able to get letsencrypt cert by looking at `examples/certbot/certbot.go` with dns-01 challenge.

Now the question is how do I renew the the cert? I can't seem to find the renew methods on the client, which suggests that renewal process is using the same mechanisms as issuing a new one. Are the steps exactly the same or ...?

Thanks a lot in advance!

**Comment by eggsampler** [comment]
No problem at all, glad this helps!

To renew, you just issue a new certificate. As long as you're not bumping up against the server rate limits that's all you need to do. Renewal is not really a direct concept, it's just a new order as far as the servers are concerned.

Probably want to reuse the same account credentials, and consider using the same certificate key if you need to pin the certificate.
