### ISSUE TITLE
How to specify InsecureSkipVerify when connecting to Pebble client for development?

### ISSUE THREAD

**Issue by dxjones** [eggsampler/acme#7]
I am trying to use this package to connect to the LetsEncrypt/Pebble server during development.

When I try the example "certbot" code, it works for the LetsEncrypt staging server, ... but it fails for the LetsEncrypt/Pebble server (since I presume Pebble signs its own certificates, and therefore the CA is not a recognized authority).

`2018/11/02 23:11:49 Error connecting to acme directory: acme: error fetching response: Get https://localhost:14000/dir: x509: certificate signed by unknown authority`

During the TLS handshake between the example "certbot" code and the Pebble server, ... how can I specify the InsecureSkipVerify option??  I can't find any way in this ACME package to pass this option when creating the client.

Can this option be supported in this ACME package?  It would really help when developing new code.

**Comment by eggsampler** [comment]
Hi,

There are a couple of options which can be given when initialising the client. These can be seen in the [options.go](https://github.com/eggsampler/acme/blob/master/options.go) file.

The option `WithInsecureSkipVerify` can be used for exactly this scenario. An example of the option being used to test against pebble can be seen [here](https://github.com/eggsampler/acme/blob/797c6f352b291db17bae2787305e2edb6e67f9dc/utility_test.go#L282).

**Comment by dxjones** [comment]
Thanks!  I was successful after modifying "certbot" to use this line:

`client, err := acme.NewClient(directoryUrl, acme.WithInsecureSkipVerify())`

**Comment by eggsampler** [comment]
Great to hear! I'll look at adding this into the examples and documenting the examples better.
